### PR TITLE
revamp app to refresh whole page, support cascade dropdown for norm typ and statistics

### PR DESCRIPTION
**Pull request by rbavery**
I'm unclear if this is just a case of my machine, @sfishel18 indicated page refreshes preserve state.

When I enter input into a textbox field a session id is created. when I enter into another field, a new session id is created and the previous is not found

Setting a breakpoint at `return get_session_by_id(session_id)` shows the following when I edit two fields, instead of using the same session id, a new id is created because the initial id disappears on page refresh

```
session_id
'995b8dad-67d3-4ecd-bb76-3d8ed3d6076a'
session_id
'848e8fe7-3707-4579-a7fb-a773c5abf694'
fasthtml_session
{'session_id': '848e8fe7-3707-4579-a7fb-a773c5abf694'}
```
EDIT
this was caused by me having a hardcoded session path. I think it didn't affect @sfishel18 because he didn't have the path and it defaulted to storing the session in a way that preserved the session on refresh. after removing this hardcode I see the session cookie

### CODE REVIEW

**Comment by rbavery** [comment]
for some reason, the following is broken:

1. selecting z-score
2. then filling out the statistic field
3. selecting min-max
4. then switching back to z-score does not trigger the old mean and statistic input to fill the form even though it shows up in the form input, so mean and std stats don't show up in the json view when they should.

**Comment by rbavery** [comment]
I'm also now noticing that because we refresh the whole page on input, entering long number values into the `Input Dimension Size` or other number inputs can refresh the whole page. if the delay isn't long enough, the values get scrambled as you enter.

EDIT: fixed by not rendering the page twice. I stopped returning session_form in the submit post and everything now seems to be working as before except the cascading inputs for norm type and statistics.

**Comment by rbavery** [comment]
I think the remaining issue with the norm type input might be solved by adding an endpoint that is triggered by the norm type input that replaces the norm type field with norm type and the correct statistics field.

**Comment by sfishel18** [comment]
> I'm also now noticing that because we refresh the whole page on input, entering long number values into the `Input Dimension Size` or other number inputs can refresh the whole page. if the delay isn't long enough, the values get scrambled as you enter.
> 
> EDIT: fixed by not rendering the page twice. I stopped returning session_form in the submit post and everything now seems to be working as before except the cascading inputs for norm type and statistics.

you could either fix it this way, which as you mention below means you're back to figuring out a custom endpoint for the statistics field.  or, you could update the `hx_trigger` for the form to `change` instead of `input delay 200ms`. then you wouldn't have to deal with the form submitting while the user types, which should make it possible to re-render the form on every submit. but the user experience is slightly different since now the results output won't update until they press enter or move focus to a new field.

it's your call whether you want to add the complexity of a new endpoint to render the statistics field in order to support the output updating as the user types.

**Comment by sfishel18** [comment]
> for some reason, the following is broken:
> 
> 1. selecting z-score
> 2. then filling out the statistic field
> 3. selecting min-max
> 4. then switching back to z-score does not trigger the old mean and statistic input to fill the form even though it shows up in the form input, so mean and std stats don't show up in the json view when they should.

i don't know enough about the domain to propose how to fix this, but i think the problems is that the data in the session is getting out of sync with the data in the pystac model, that happens here in `submit`:

```python
    ml_model_metadata = construct_ml_model_properties(d)
    assets = construct_assets(session['stac_format_d'].get('assets'))
    item = create_pystac_item(ml_model_metadata, assets)
    return session_form(session), prettyJsonTemplate(item)
```

the `construct_ml_model_properties` / `construct_assets` / `create_pystac_item` functions are applying some special logic to convert the posted data into the pystac item, but the result of that transformation is not applied to what's in `session`

i don't know how difficult this would be to pull off, but imo things would be easier to reason about if there was a single source of truth - probably in the form of a pystac item - that gets stored exactly as-is in the session. and then the form and the output are both rendered out from that

**Comment by rbavery** [comment]
> i don't know how difficult this would be to pull off, but imo things would be easier to reason about if there was a single source of truth - probably in the form of a pystac item - that gets stored exactly as-is in the session. and then the form and the output are both rendered out from that

Unfortunately this is too difficult to pull off. Originally this was my motivation for building the form directly from the JSON schema. Because the mlm item and extensions to the STAC schema doesn't have a full pydantic model describing them, I can't easily write templates that are built from the pydantic models that account for all the metadata fields.

**Comment by rbavery** [comment]
For now I'm just showing both stats entries on the page with instructions. The second oob swap felt compelling since I could switch between both norm types and show different fields and they would update the viewer correctly.  But whenever page refreshes occurred info got lost, the newly created fields disappeared. This feels possibly related to https://htmx.org/attributes/hx-swap-oob/#nested-oob-swaps for correctly only updating the target of the nested oob swap but not sure how to set this setting in fasthtml.

**Pull request merged**
