### PR TITLE
allow editing JSON across multiple pages with session, clear form button

### PR DESCRIPTION
**Pull request by rbavery**
this isn't the best UI in the world but it works and is responsive to user input and pretty easy to follow, but feedback and help on the UI experience is much appreciated. merging to keep progress going cc @sfishel18

### CODE REVIEW

**Comment by sfishel18** [comment]
it looks like if you want to preserve the form state between page reloads, you can read the session data in the route that renders the form, i.e. in `homepage` change this line

```py
inputTemplate(label="Architecture", name="architecture", val='', input_type='text'),
```

to this:

```py
inputTemplate(label="Architecture", name="architecture", val=session['result_d'].get('architecture', ''), input_type='text'),
```

and the same approach could be applied to showing the results div on the initial page load if you factor out a helper function to render that from the current session state, that you call from `homepage` and from `submit`

**Comment by sfishel18** [comment]
also a couple of ux/visual suggestions:

1. we probably want a button somewhere to clear out all of the information in the current session
2. now that the json is bigger the result display can end up taller than the window and there's no way to scroll it, try changing `outputTemplate` to this:

```py
def outputTemplate(id):
    return Div(
        Div(id=id, style="position: fixed; right: 50px; width: 500px; height: calc(100vh - 150px); overflow: auto;"),
        style="position: relative;"
    )
```

**Comment by rbavery** [comment]
> also a couple of ux/visual suggestions:
> 
> 1. we probably want a button somewhere to clear out all of the information in the current session
> 2. now that the json is bigger the result display can end up taller than the window and there's no way to scroll it, try changing `outputTemplate` to this:
> 
> ```python
> def outputTemplate(id):
>     return Div(
>         Div(id=id, style="position: fixed; right: 50px; width: 500px; height: calc(100vh - 150px); overflow: auto;"),
>         style="position: relative;"
>     )
> ```


Added a button but it nearly disappears when clicked for some reason I don't understand. it seems to have an effect on clearing the session but it is currently only noticeable with a page refresh. maybe I can trigger a refresh of the page with the button or reset the form from the button

**Comment by rbavery** [comment]
> it looks like if you want to preserve the form state between page reloads, you can read the session data in the route that renders the form, i.e. in `homepage` change this line
> 
> ```python
> inputTemplate(label="Architecture", name="architecture", val='', input_type='text'),
> ```
> 
> to this:
> 
> ```python
> inputTemplate(label="Architecture", name="architecture", val=session['result_d'].get('architecture', ''), input_type='text'),
> ```
> 
> and the same approach could be applied to showing the results div on the initial page load if you factor out a helper function to render that from the current session state, that you call from `homepage` and from `submit`

I addressed at the form level with the form_fill function from FastHTML, so we don't need to interact with the session object at each form field

**Comment by rbavery** [comment]
I tried adding a Button in the Grid that when clicked triggers `session.clear` but I wasn't sure how to also get it to clear the state in the result div. It would only show session clears on refresh. I'm getting a bit confused managing state with htmx (sending and receiving html responses) and the session state object I think. If you have some time tomorrow @sfishel18 would love to pair on this.

**Pull request merged**
